
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class floatexp
    extends expAbstractNode
{

    public final floatToken float0;

    public floatexp(floatToken float0) {
        this.float0 = float0;
    }

    @Override
    public int getLine() {
        return float0 .getLine();
    }

    @Override
    public int getPos() {
        return float0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ float0 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof floatexp)) {
            return false;
        }
        floatexp castResult = ((floatexp) o);
        if (!this.float0 .equals(castResult.float0)) {
            return false;
        }
        return true;
    }

}
