package language.implementation.symbols.declarations;

import language.implementation.Visitor;
import language.implementation.symbols.Declaration;
import language.implementation.symbols.terminals.Identifier;

public class FuncDecl extends Declaration{
	private static final long serialVersionUID = 1L;

	public final Identifier id;
	
	@SuppressWarnings("unchecked")
	public FuncDecl(Identifier id) {
		super(FuncDecl.class, Identifier.class);
		this.id = id;
	}

	@Override
	public void accept(Visitor visitor) {
		visitor.visit(this);
	}

	//generated by eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	//generated by eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FuncDecl other = (FuncDecl) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	
	
}
