
package language.parser;

import language.parser.framework.Symbol;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public enum Symbols
    implements Symbol
{

    EOF,
    _PUNCTUATION8("`!'"),
    _PUNCTUATION7("`)'"),
    _PUNCTUATION6("`('"),
    _PUNCTUATION5("`='"),
    _PUNCTUATION4("`^'"),
    _PUNCTUATION3("`/'"),
    _PUNCTUATION2("`*'"),
    _PUNCTUATION1("`-'"),
    _PUNCTUATION0("`+'"),
    ID,
    INT,
    FLOAT,
    ERROR,
    ASSIGN,
    BINOP,
    UOP,
    EXP,
    IDLIST;
    private final String name;

    private Symbols(String name) {
        this.name = name;
    }

    private Symbols() {
        this.name = null;
    }

    @Override
    public String toString() {
        if (name == null) {
            return super.toString();
        }
        return name;
    }

    @Override
    public int type() {
        return this.ordinal();
    }

}
