
package language.parser.nodes;

import language.parser.Symbols;
import language.parser.Visitor;
import language.parser.framework.Symbol;
import language.parser.framework.Token;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class _Punctuation11Token
    extends Token<Visitor>
{


    public _Punctuation11Token(String text, int line, int pos) {
        super(text, line, pos);
    }

    public _Punctuation11Token() {
        super();
    }

    @Override
    public void accept(Visitor visitor) {
        //do nothing
    }

    @Override
    public Symbol symbol() {
        return Symbols._PUNCTUATION11;
    }

    @Override
    public String toString() {
        return symbol().toString();
    }

}
