
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class binopexp
    extends expAbstractNode
{

    public final binopAbstractNode binop0;

    public binopexp(binopAbstractNode binop0) {
        this.binop0 = binop0;
    }

    @Override
    public int getLine() {
        return binop0 .getLine();
    }

    @Override
    public int getPos() {
        return binop0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ binop0 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof binopexp)) {
            return false;
        }
        binopexp castResult = ((binopexp) o);
        if (!this.binop0 .equals(castResult.binop0)) {
            return false;
        }
        return true;
    }

}
