
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class idlist_Punctuation5expassign
    extends assignAbstractNode
{

    public final idlistAbstractNode idlist0;
    public final expAbstractNode exp1;

    public idlist_Punctuation5expassign(idlistAbstractNode idlist0, _Punctuation5Token _punctuation51, expAbstractNode exp2) {
        this.idlist0 = idlist0;
        this.exp1 = exp2;
    }

    @Override
    public int getLine() {
        return idlist0 .getLine();
    }

    @Override
    public int getPos() {
        return idlist0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ idlist0 .hashCode());
        hash = ((hash* 13)+ exp1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this.equals(o)) {
            return true;
        }
        if (o.equals(null)) {
            return false;
        }
        if (!(o instanceof idlist_Punctuation5expassign)) {
            return false;
        }
        idlist_Punctuation5expassign castResult = ((idlist_Punctuation5expassign) o);
        if (!this.idlist0 .equals(castResult.idlist0)) {
            return false;
        }
        if (!this.exp1 .equals(castResult.exp1)) {
            return false;
        }
        return true;
    }

}
