
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class IdListHead
    extends idlistAbstractNode
{

    public final idToken id0;

    public IdListHead(idToken id0) {
        this.id0 = id0;
    }

    @Override
    public int getLine() {
        return id0 .getLine();
    }

    @Override
    public int getPos() {
        return id0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ id0 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof IdListHead)) {
            return false;
        }
        IdListHead castResult = ((IdListHead) o);
        if (!this.id0 .equals(castResult.id0)) {
            return false;
        }
        return true;
    }

}
