
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class Subtract
    extends binopAbstractNode
{

    public final expAbstractNode exp0;
    public final expAbstractNode exp1;

    public Subtract(expAbstractNode exp0, _Punctuation1Token _punctuation11, expAbstractNode exp2) {
        this.exp0 = exp0;
        this.exp1 = exp2;
    }

    @Override
    public int getLine() {
        return exp0 .getLine();
    }

    @Override
    public int getPos() {
        return exp0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ exp0 .hashCode());
        hash = ((hash* 13)+ exp1 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof Subtract)) {
            return false;
        }
        Subtract castResult = ((Subtract) o);
        if (!this.exp0 .equals(castResult.exp0)) {
            return false;
        }
        if (!this.exp1 .equals(castResult.exp1)) {
            return false;
        }
        return true;
    }

}
