
package language.parser.nodes;

import language.parser.Visitor;


/**
 * This class was generated by the LRPaGe parser generator v1.0 using the com.sun.codemodel library.
 * 
 * <P>LRPaGe is available from https://github.com/tbepler/LRPaGe.
 * <P>CodeModel is available from https://codemodel.java.net/.
 * 
 */
public class uopexp
    extends expAbstractNode
{

    public final uopAbstractNode uop0;

    public uopexp(uopAbstractNode uop0) {
        this.uop0 = uop0;
    }

    @Override
    public int getLine() {
        return uop0 .getLine();
    }

    @Override
    public int getPos() {
        return uop0 .getPos();
    }

    @Override
    public void accept(Visitor visitor) {
        visitor.visit(this);
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = ((hash* 13)+ uop0 .hashCode());
        hash = ((hash* 13)+ getClass().hashCode());
        return hash;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (null == o) {
            return false;
        }
        if (!(o instanceof uopexp)) {
            return false;
        }
        uopexp castResult = ((uopexp) o);
        if (!this.uop0 .equals(castResult.uop0)) {
            return false;
        }
        return true;
    }

}
